const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx=vm.createContext({Date,console});for(const file of ['macro.js','market-board.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx);
const run=code=>vm.runInContext(code,ctx);
assert.equal(run('boardComposite([{score:null},{score:null}]).score'),null);
assert.equal(run('boardComposite([{score:1},{score:1}]).label'),'판단 보류');
assert.equal(run('boardComposite([{score:1},{score:1},{score:0},{score:null}]).score'),83);
assert.equal(run('boardComposite([{score:-1},{score:-1},{score:0}]).label'),'Risk-Off 우세');
assert.equal(run('boardFresh("2026-08-01",7,Date.parse("2026-09-10"))'),false);
assert.equal(run('boardFresh("2026-09-11",7,Date.parse("2026-09-10"))'),false);
assert.equal(run('boardSignals({},Date.parse("2026-09-10")).filter(x=>x.score!==null).length'),0);
assert.equal(run('boardTrend([{date:"2026-09-01",value:10},{date:"2026-09-08",value:15}],1)'),5);
assert.equal(run('boardTrend([{date:"2026-08-01",value:10},{date:"2026-09-08",value:15}],1)'),null);
assert.equal(run('boardTrend([{date:"2026-09-08",value:15}],13)'),null);
assert.equal(run('boardUpcoming([{at:"2026-09-10T00:00:00Z"},{at:"2026-09-17T00:00:00Z"},{at:"2026-09-09T23:59:59Z"}],Date.parse("2026-09-10T00:00:00Z")).length'),1);
assert.match(run('boardTime("2026-09-11T08:30:00-04:00")'),/21:30/);
assert.match(run('boardTime("2026-11-10T08:30:00-05:00")'),/22:30/);
console.log('Passed: missing/stale signals, coverage, score, calendar boundaries, KST daylight saving, weekly changes.');
const dates=Array.from({length:50},(_,i)=>new Date(Date.UTC(2026,6,1+i)).toISOString().slice(0,10));
const fixture={series:Object.fromEntries(['DGS2','DGS5','DGS10','DGS30'].map(id=>[id,{rows:dates.map((date,i)=>({date,value:4+(i%2)*0.04}))}]))};
ctx.fixture=fixture;
const actualProxy=run('boardBondProxy(fixture)');
assert.equal(actualProxy.length,29);
const changes=Array.from({length:21},(_,i)=>i%2===0?4:-4),mean=changes.reduce((a,b)=>a+b)/21;
const expected=1.1255*Math.sqrt(changes.reduce((a,b)=>a+(b-mean)**2,0)/21)*Math.sqrt(252);
assert(Math.abs(actualProxy[0].value-expected)<1e-10);
assert.equal(run('boardBondProxy({series:{DGS2:fixture.series.DGS2}}).length'),0);
assert.equal(run('boardBondProxy({series:Object.fromEntries(Object.entries(fixture.series).map(([id,s])=>[id,{rows:s.rows.slice(0,21)}]))}).length'),0);
assert.equal(run('boardBondRegime(79.9).score'),1);assert.equal(run('boardBondRegime(80).score'),0);
assert.equal(run('boardBondRegime(100).score'),-1);assert.equal(run('boardBondRegime(120).index'),3);
assert.equal(run('boardSignals({macro:fixture},Date.parse("2026-08-20")).at(-1).score'),1);
assert.equal(run('boardSignals({macro:fixture},Date.parse("2026-09-10")).at(-1).score'),null);
const flat=JSON.parse(JSON.stringify(fixture));for(const s of Object.values(flat.series))for(const row of s.rows)row.value=4;
ctx.flat=flat;assert.equal(run('boardBondProxy(flat).at(-1).value'),55);
const huge=JSON.parse(JSON.stringify(fixture));for(const s of Object.values(huge.series))s.rows.forEach((r,i)=>r.value=i%2?10:0);
ctx.huge=huge;assert.equal(run('boardBondProxy(huge).at(-1).value'),180);
const missing=JSON.parse(JSON.stringify(fixture));missing.series.DGS5.rows[10].value=null;ctx.missing=missing;
assert.equal(run('boardBondProxy(missing).length'),28);
console.log('Passed: original proxy formula, 22-observation minimum, common dates, clipping, traffic lights, stale score exclusion.');
const histData={macro:fixture,fear:{fear_and_greed_historical:{data:dates.map(date=>({x:Date.parse(date),y:60}))}},options:{rows:dates.map(date=>({date,equity_pc:0.5}))}};
ctx.histData=histData;
const history=run('boardHistory(histData,Date.parse("2026-08-19T23:59:59.999Z"),90)');
assert.equal(history.length,90);assert.equal(history[0].score,null);
assert.equal(history.at(-1).score,run('boardComposite(boardSignals({macro:fixture,fear:{fear_and_greed:{score:60,timestamp:"2026-08-19"}},options:histData.options},Date.parse("2026-08-19T23:59:59.999Z"))).score'));
const future=JSON.parse(JSON.stringify(histData));future.options.rows.push({date:'2027-01-01',equity_pc:9});future.fear.fear_and_greed={timestamp:'2027-01-01',score:0};ctx.future=future;
assert.equal(JSON.stringify(run('boardHistory(future,Date.parse("2026-08-19T23:59:59.999Z"),90)')),JSON.stringify(history));
assert(run('boardHistory({},Date.parse("2026-08-19"),90).every(r=>r.score===null)'));
console.log('Passed: historical coverage, missing periods, current score parity, future observations excluded.');
